# Generated by Django 4.0 on 2021-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtable',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dealtable',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
