# Generated by Django 4.0 on 2021-12-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_dealtable_endtime_alter_dealtable_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtable',
            name='endTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealtable',
            name='startTime',
            field=models.DateField(),
        ),
    ]
